version: 2
jobs:
  build:
    working_directory: ~/MoodleSites
    docker:
      - image: circleci/golang:1.8
    # environment:
    #   - BUCKET_NAME: "moodle.sites.lambda.deployment"
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS

    - restore_cache:
        keys:
          - v1-pkg-cache

    # # Normally, this step would be in a custom primary image;
    # # we've added it here for the sake of explanation.
    # - run: go get github.com/lib/pq
    # - run: go get github.com/mattes/migrate
    - run: go get github.com/jstemmer/go-junit-report

  
    - run:
        name: Run unit tests
        # environment:
        #   CONTACTS_DB_URL: "postgres://circleci-demo-go@localhost:5432/circle_test?sslmode=disable"
        #   CONTACTS_DB_MIGRATIONS: /go/src/github.com/CircleCI-Public/circleci-demo-go/db/migrations
        command: |
          trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          make test | tee ${TEST_RESULTS}/go-test.out
    - run: make

    - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"

    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output

    - store_test_results:
        path: /tmp/test-results